# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# coding: utf-8

User.create(email: "test1@test.com", name: "test1", password: "testtest", introduction: "", created_at: "2023-09-15 13:05:22.433764000 +0000", updated_at: "2023-09-15 13:43:41.219165000 +0000")
User.create(email: "test2@test.com", name: "test2", password: "testtest", introduction: "", created_at: "2023-09-15 13:05:22.433764000 +0000", updated_at: "2023-09-15 13:43:41.219165000 +0000")
User.create(email: "test3@test.com", name: "test3", password: "testtest", introduction: "", created_at: "2023-09-15 13:05:22.433764000 +0000", updated_at: "2023-09-15 13:43:41.219165000 +0000")
User.create(email: "test4@test.com", name: "test4", password: "testtest", introduction: "", created_at: "2023-09-15 13:05:22.433764000 +0000", updated_at: "2023-09-15 13:43:41.219165000 +0000")
User.create(email: "test5@test.com", name: "test5", password: "testtest", introduction: "", created_at: "2023-09-15 13:05:22.433764000 +0000", updated_at: "2023-09-15 13:43:41.219165000 +0000")
User.create(email: "test6@test.com", name: "test6", password: "testtest", introduction: "", created_at: "2023-09-15 13:05:22.433764000 +0000", updated_at: "2023-09-15 13:43:41.219165000 +0000")
User.create(email: "test7@test.com", name: "test7", password: "testtest", introduction: "", created_at: "2023-09-15 13:05:22.433764000 +0000", updated_at: "2023-09-15 13:43:41.219165000 +0000")
User.create(email: "test8@test.com", name: "test8", password: "testtest", introduction: "", created_at: "2023-09-15 13:05:22.433764000 +0000", updated_at: "2023-09-15 13:43:41.219165000 +0000")
User.create(email: "test9@test.com", name: "test9", password: "testtest", introduction: "", created_at: "2023-09-15 13:05:22.433764000 +0000", updated_at: "2023-09-15 13:43:41.219165000 +0000")
User.create(email: "test10@test.com", name: "test10", password: "testtest", introduction: "", created_at: "2023-09-15 13:05:22.433764000 +0000", updated_at: "2023-09-15 13:43:41.219165000 +0000")

Book.create(title: "未来のプログラマーへの道",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "占星術の基本",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "手芸の楽しみ",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "プログラミングの魔法",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "星座占いの秘密",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "かぎ針編みマスタークラス",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "Pythonプログラミング入門",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "恋愛占いのアート",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "野菜栽培のススメ",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "C++プログラミングの基本",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "タロットカードの解読",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "ニットの技術とアイディア",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "データ構造とアルゴリズムの本",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "幸せな星座の組み合わせ",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "刺繍のマスターガイド",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "Javaプログラミングの実践",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "占いの歴史",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "クロスステッチの楽しみ",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "デザインパターンの実践ガイド",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "12星座の深層心理学",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "トピックモデリングの実践ガイド",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "タロット占いのプロセス",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "アンドロイドアプリ開発の手引き",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "手芸マスターのためのクリエイティブソース",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "ディープラーニングの基本",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "乙女座の魅力",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "データベース設計とSQLクエリ",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "クロスステッチの美",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "ブロックチェーン技術の全解説",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "数学とアルゴリズムの世界",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "プログラミング言語の歴史",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "占いの魔法と秘密",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "手芸作品のアイディア集",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "ソフトウェアエンジニアリングの基礎",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "星座と恋愛の心理学",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "刺繍デザインのアート",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "Pythonデータサイエンス入門",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "タロットカードの魔法の使い方",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "編み物の楽しさ",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "アルゴリズムとデータ構造の実践ガイド",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "データサイエンスの世界への案内",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "占星術の魔法と秘訣",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "手芸のアートとクラフト",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "プログラミングの奥深い世界",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "星座占いのプロセスと解釈",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "刺繍デザインのアイデアブック",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "Javaプログラミングの実践ガイド",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "タロットカードの謎",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "針仕事の楽しさと技術",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "データベース管理とSQLマスター",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "プログラムの魔法とアルゴリズム",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "星座占いの深層心理学",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "手芸のクリエイティブなアイデア",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "Pythonプログラミングの実践",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "タロットカードの解釈と予測",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "刺繍の美しさと技術",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "データ分析と機械学習の基本",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "占いのアートと実践",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "野菜栽培の楽しみ",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "C言語プログラミングの入門",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "デザインパターンの実践ガイド",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "星座と運命の結びつき",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "手芸アイディアの宝庫",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "Rubyプログラミングの魅力",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "占い術の秘密と技術",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "刺繍デザインの極意",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "データサイエンスの深淵",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "タロットカードの魔法的使い方",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "陶芸の楽しさと技術",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "JavaScriptプログラミングの基礎",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "データベース設計のマスタークラス",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "星座占いと愛の秘密",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "手芸作品の魅力的なデザイン",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "Javaプログラミングの魔法",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "タロットカードの宇宙への旅",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "刺繍のアートとクリエイティビティ",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "機械学習の実践ガイド",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "占星術の深層解析",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "陶芸の楽しさと技術の探求",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "Web開発の基本と実践",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "プログラミングの未来を切り拓く",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "星座占いと運命の結びつき",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "手芸のクリエイティブなアイデア集",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "Pythonプログラミングのマスターガイド",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "タロットカードの魔法的解釈",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "刺繍の美しさとテクニック",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "データサイエンスの基本と応用",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "占い術の秘密と実践",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "園芸の楽しみと知識",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "C#プログラミングの実践入門",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "データベース設計とSQLの実践ガイド",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "星座と幸運の法則",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "手芸のアートとアイディア",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "Rubyプログラミングの基礎と実践",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "タロットカードの魅力的な解読",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "刺繍のテクニックとクリエイティビティ",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "データ分析の奥深さ",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "占星術の深層心理学",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "野菜栽培の楽しみと実践",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
Book.create(title: "JavaScriptプログラミングのマスタークラス",body: "テスト",user_id: rand(1..10),created_at: Time.current .ago(rand(0..14).days),updated_at: Time.current)
